name: GitHub API Call Workflow

on:
  workflow_dispatch: # This allows the workflow to be manually triggered

jobs:
  api_call_job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository (not strictly necessary for API call but included as a standard practice)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Make an API call using the GitHub API to list the latest commits
      - name: GitHub API Call
        id: github_api
        run: |
          # Replace with the repository and owner you want to query
          USER_NAME="darshanmadesh"

          # Make the API request to fetch the latest commits
          response=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/https://api.github.com/users/$USER_NAME/events")
          
          # Output the API response (the latest 5 commits)
          echo "$response"
