name: GitHub API Call Workflow

on:
  workflow_dispatch: # This allows the workflow to be manually triggered

jobs:
  api_call_job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository (not strictly necessary for API call but included as a standard practice)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Make an API call using the GitHub API to list the latest commits
      - name: GitHub API Call
        id: github_api
        run: |
          # Replace with the repository and owner you want to query
          REPO_OWNER="owner-name"
          REPO_NAME="repo-name"

          # Make the API request to fetch the latest commits
          response=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/commits?per_page=5")
          
          # Output the API response (the latest 5 commits)
          echo "$response"

          # Save the commit SHAs for further processing if needed
          commits=$(echo "$response" | jq -r '.[].sha')
          echo "Latest Commit SHAs: $commits"
          
          # Set the output of the step to be used later in the workflow
          echo "::set-output name=commits::$commits"

      # Step 3: Print the commits (for logging or future use)
      - name: Output Commits
        run: |
          echo "The latest 5 commits are: ${{ steps.github_api.outputs.commits }}"
